package com.trust3.xcpro.map

internal object MapRenderSurfaceDiagnosticsStatusFormatter {
    fun buildStatus(
        snapshot: MapRenderSurfaceDiagnostics.Snapshot,
        header: String
    ): String =
        buildString {
            append(header).append(":\n")
            append("- Repaint Requests: ${snapshot.repaintRequestCount}\n")
            append("- Forced Immediate Repaint Requests: ${snapshot.forcedImmediateRepaintRequestCount}\n")
            append("- Repaint Dispatches: ${snapshot.repaintDispatchCount}\n")
            append("- Render Frame Callbacks: ${snapshot.renderFrameCallbackCount}\n")
            append("- Posted Dispatch Scheduled: ${snapshot.postedDispatchScheduledCount}\n")
            append("- Posted Dispatch Dropped: ${snapshot.postedDispatchDroppedCount}\n")
            append("- Immediate Dispatches: ${snapshot.immediateDispatchCount}\n")
            append("- Pending Dispatch Cleared: ${snapshot.pendingDispatchClearedCount}\n")
            append("- Render Frames Delivered: ${snapshot.renderFrameDeliveredCount}\n")
            append("- Frames Rendered: ${snapshot.frameRenderedCount}\n")
            append("- Display Frame Dispatch Allowed: ${snapshot.displayFrameDispatchAllowedCount}\n")
            append("- Display Frame Pre-Dispatch Suppressed: ${snapshot.displayFramePreDispatchSuppressedCount}\n")
            append("- Display Frame Render Skipped: ${snapshot.displayFrameRenderSkippedCount}\n")
            append("- Display Frame No-Op Skips: ${snapshot.displayFrameNoOpSkippedCount}\n")
            append("- Display Pose Render Applied: ${snapshot.displayPoseRenderAppliedCount}\n")
            append("- Monotonic Raw Fix Inputs: ${snapshot.monotonicRawFixInputCount}\n")
            append("- Wall Raw Fix Inputs: ${snapshot.wallRawFixInputCount}\n")
            append("- Replay Raw Fix Inputs: ${snapshot.replayRawFixInputCount}\n")
            append("- Lifecycle Resume Forced Frames: ${snapshot.lifecycleResumeForcedFrameCount}\n")
            append("- MapView Attach Count: ${snapshot.mapViewAttachCount}\n")
            append("- MapView Clear Count: ${snapshot.mapViewClearCount}\n")
            append("- MapView Swap Count: ${snapshot.mapViewSwapCount}\n")
            append("- Last Repaint Request Mono Ms: ${snapshot.lastRepaintRequestMonoMs}\n")
            append("- Last Repaint Dispatch Mono Ms: ${snapshot.lastRepaintDispatchMonoMs}\n")
            append("- Last Render Callback Mono Ms: ${snapshot.lastRenderFrameCallbackMonoMs}\n")
            append("- Last Render Delivered Mono Ms: ${snapshot.lastRenderFrameDeliveredMonoMs}\n")
            append("- Last Frame Rendered Mono Ms: ${snapshot.lastFrameRenderedMonoMs}\n")
            append("- Last Monotonic Raw Fix Timestamp Ms: ${snapshot.lastMonotonicRawFixTimestampMs}\n")
            append("- Last Wall Raw Fix Timestamp Ms: ${snapshot.lastWallRawFixTimestampMs}\n")
            append("- Last Replay Raw Fix Timestamp Ms: ${snapshot.lastReplayRawFixTimestampMs}\n")
            append("- Last Lifecycle Resume Forced Frame Mono Ms: ${snapshot.lastLifecycleResumeForcedFrameMonoMs}\n")
            append("- Last MapView Attach Mono Ms: ${snapshot.lastMapViewAttachMonoMs}\n")
            append("- Last MapView Clear Mono Ms: ${snapshot.lastMapViewClearMonoMs}\n")
            append("- Display Frame Dispatch Allowed Reasons: ")
                .append(snapshot.displayFrameDispatchAllowedReasons.toDispatchReasonString())
                .append("\n")
            append("- Display Frame Pre-Dispatch Suppression Reasons: ")
                .append(snapshot.displayFramePreDispatchSuppressionReasons.toSuppressionReasonString())
                .append("\n")
            append("- Display Frame Render Skip Reasons: ")
                .append(snapshot.displayFrameRenderSkipReasons.toRenderSkipReasonString())
                .append("\n")
            append("- Live Raw Fix Input Interval Buckets: ")
                .append(snapshot.liveRawFixInputIntervalBuckets.toCompactString())
                .append("\n")
            append("- Wall Raw Fix Input Interval Buckets: ")
                .append(snapshot.wallRawFixInputIntervalBuckets.toCompactString())
                .append("\n")
            append("- Replay Raw Fix Input Interval Buckets: ")
                .append(snapshot.replayRawFixInputIntervalBuckets.toCompactString())
                .append("\n")
            append("- Render Frame Delivered Interval Buckets: ")
                .append(snapshot.renderFrameDeliveredIntervalBuckets.toCompactString())
                .append("\n")
            append("- Frame Rendered Interval Buckets: ")
                .append(snapshot.frameRenderedIntervalBuckets.toCompactString())
                .append("\n")
        }

    fun buildCompactStatus(
        snapshot: MapRenderSurfaceDiagnostics.Snapshot,
        reason: String,
        token: String
    ): String =
        buildString {
            append(token)
            append(" reason=").append(reason)
            append(" repaint_requests=").append(snapshot.repaintRequestCount)
            append(" forced_immediate_repaint_requests=")
                .append(snapshot.forcedImmediateRepaintRequestCount)
            append(" repaint_dispatches=").append(snapshot.repaintDispatchCount)
            append(" render_frame_callbacks=").append(snapshot.renderFrameCallbackCount)
            append(" posted_dispatch_scheduled=").append(snapshot.postedDispatchScheduledCount)
            append(" posted_dispatch_dropped=").append(snapshot.postedDispatchDroppedCount)
            append(" immediate_dispatches=").append(snapshot.immediateDispatchCount)
            append(" pending_dispatch_cleared=").append(snapshot.pendingDispatchClearedCount)
            append(" render_frames_delivered=").append(snapshot.renderFrameDeliveredCount)
            append(" frames_rendered=").append(snapshot.frameRenderedCount)
            append(" display_frame_dispatch_allowed=")
                .append(snapshot.displayFrameDispatchAllowedCount)
            append(" display_frame_dispatch_allowed_reasons=")
                .append(snapshot.displayFrameDispatchAllowedReasons.toDispatchReasonString())
            append(" display_frame_pre_dispatch_suppressed=")
                .append(snapshot.displayFramePreDispatchSuppressedCount)
            append(" display_frame_pre_dispatch_suppression_reasons=")
                .append(snapshot.displayFramePreDispatchSuppressionReasons.toSuppressionReasonString())
            append(" display_frame_render_skipped=")
                .append(snapshot.displayFrameRenderSkippedCount)
            append(" display_frame_render_skip_reasons=")
                .append(snapshot.displayFrameRenderSkipReasons.toRenderSkipReasonString())
            append(" display_frame_noop_skips=").append(snapshot.displayFrameNoOpSkippedCount)
            append(" display_pose_render_applied=").append(snapshot.displayPoseRenderAppliedCount)
            append(" monotonic_raw_fix_inputs=").append(snapshot.monotonicRawFixInputCount)
            append(" wall_raw_fix_inputs=").append(snapshot.wallRawFixInputCount)
            append(" replay_raw_fix_inputs=").append(snapshot.replayRawFixInputCount)
            append(" lifecycle_resume_forced_frames=")
                .append(snapshot.lifecycleResumeForcedFrameCount)
            append(" mapview_attach_count=").append(snapshot.mapViewAttachCount)
            append(" mapview_clear_count=").append(snapshot.mapViewClearCount)
            append(" mapview_swap_count=").append(snapshot.mapViewSwapCount)
            append(" last_repaint_request_mono_ms=").append(snapshot.lastRepaintRequestMonoMs)
            append(" last_repaint_dispatch_mono_ms=").append(snapshot.lastRepaintDispatchMonoMs)
            append(" last_render_callback_mono_ms=").append(snapshot.lastRenderFrameCallbackMonoMs)
            append(" last_render_delivered_mono_ms=").append(snapshot.lastRenderFrameDeliveredMonoMs)
            append(" last_frame_rendered_mono_ms=").append(snapshot.lastFrameRenderedMonoMs)
            append(" last_monotonic_raw_fix_timestamp_ms=")
                .append(snapshot.lastMonotonicRawFixTimestampMs)
            append(" last_wall_raw_fix_timestamp_ms=")
                .append(snapshot.lastWallRawFixTimestampMs)
            append(" last_replay_raw_fix_timestamp_ms=")
                .append(snapshot.lastReplayRawFixTimestampMs)
            append(" last_lifecycle_resume_forced_frame_mono_ms=")
                .append(snapshot.lastLifecycleResumeForcedFrameMonoMs)
            append(" last_mapview_attach_mono_ms=").append(snapshot.lastMapViewAttachMonoMs)
            append(" last_mapview_clear_mono_ms=").append(snapshot.lastMapViewClearMonoMs)
            append(" live_raw_fix_input_interval_buckets=")
                .append(snapshot.liveRawFixInputIntervalBuckets.toCompactString())
            append(" wall_raw_fix_input_interval_buckets=")
                .append(snapshot.wallRawFixInputIntervalBuckets.toCompactString())
            append(" replay_raw_fix_input_interval_buckets=")
                .append(snapshot.replayRawFixInputIntervalBuckets.toCompactString())
            append(" render_frame_delivered_interval_buckets=")
                .append(snapshot.renderFrameDeliveredIntervalBuckets.toCompactString())
            append(" frame_rendered_interval_buckets=")
                .append(snapshot.frameRenderedIntervalBuckets.toCompactString())
        }
}

private fun Map<MapRenderSurfaceDiagnostics.DisplayFrameDispatchReason, Long>.toDispatchReasonString(): String =
    entries.joinToString(",") { (reason, count) -> "${reason.key}=$count" }

private fun Map<MapRenderSurfaceDiagnostics.DisplayFramePreDispatchSuppressionReason, Long>.toSuppressionReasonString(): String =
    entries.joinToString(",") { (reason, count) -> "${reason.key}=$count" }

private fun Map<MapRenderSurfaceDiagnostics.DisplayFrameRenderSkipReason, Long>.toRenderSkipReasonString(): String =
    entries.joinToString(",") { (reason, count) -> "${reason.key}=$count" }
