package com.example.xcpro.thermalling

const val THERMALLING_ENABLED_DEFAULT = false
const val THERMALLING_SWITCH_TO_THERMAL_MODE_DEFAULT = true
const val THERMALLING_ZOOM_ONLY_FALLBACK_WHEN_THERMAL_HIDDEN_DEFAULT = true
const val THERMALLING_ENTER_DELAY_DEFAULT_SECONDS = 5
const val THERMALLING_EXIT_DELAY_DEFAULT_SECONDS = 8
const val THERMALLING_APPLY_ZOOM_ON_ENTER_DEFAULT = true
const val THERMALLING_APPLY_CONTRAST_MAP_ON_ENTER_DEFAULT = false
const val THERMALLING_ZOOM_LEVEL_DEFAULT = 13.0f
const val THERMALLING_REMEMBER_MANUAL_ZOOM_IN_SESSION_DEFAULT = true
const val THERMALLING_RESTORE_PREVIOUS_MODE_ON_EXIT_DEFAULT = true
const val THERMALLING_RESTORE_PREVIOUS_ZOOM_ON_EXIT_DEFAULT = true

const val THERMALLING_DELAY_MIN_SECONDS = 0
const val THERMALLING_DELAY_MAX_SECONDS = 30
const val THERMALLING_ZOOM_LEVEL_MIN = 7.0f
const val THERMALLING_ZOOM_LEVEL_MAX = 20.0f

data class ThermallingModeSettings(
    val enabled: Boolean = THERMALLING_ENABLED_DEFAULT,
    val switchToThermalMode: Boolean = THERMALLING_SWITCH_TO_THERMAL_MODE_DEFAULT,
    val zoomOnlyFallbackWhenThermalHidden: Boolean =
        THERMALLING_ZOOM_ONLY_FALLBACK_WHEN_THERMAL_HIDDEN_DEFAULT,
    val enterDelaySeconds: Int = THERMALLING_ENTER_DELAY_DEFAULT_SECONDS,
    val exitDelaySeconds: Int = THERMALLING_EXIT_DELAY_DEFAULT_SECONDS,
    val applyZoomOnEnter: Boolean = THERMALLING_APPLY_ZOOM_ON_ENTER_DEFAULT,
    val applyContrastMapOnEnter: Boolean = THERMALLING_APPLY_CONTRAST_MAP_ON_ENTER_DEFAULT,
    val thermalZoomLevel: Float = THERMALLING_ZOOM_LEVEL_DEFAULT,
    val rememberManualThermalZoomInSession: Boolean =
        THERMALLING_REMEMBER_MANUAL_ZOOM_IN_SESSION_DEFAULT,
    val restorePreviousModeOnExit: Boolean = THERMALLING_RESTORE_PREVIOUS_MODE_ON_EXIT_DEFAULT,
    val restorePreviousZoomOnExit: Boolean = THERMALLING_RESTORE_PREVIOUS_ZOOM_ON_EXIT_DEFAULT
)

fun clampThermallingDelaySeconds(seconds: Int): Int =
    seconds.coerceIn(THERMALLING_DELAY_MIN_SECONDS, THERMALLING_DELAY_MAX_SECONDS)

fun clampThermallingZoomLevel(zoomLevel: Float): Float =
    zoomLevel.coerceIn(THERMALLING_ZOOM_LEVEL_MIN, THERMALLING_ZOOM_LEVEL_MAX)
